name: OIDC Authentication Demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  oidc-auth-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v7
        id: artifact-upload-step
        with:
          name: my-artifact
          path: README.md

      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
